### ISSUE TITLE
ConfigParser missing

### ISSUE THREAD

**Issue by speeddragon** [ex-aws/ex_aws_sts#13]
I was getting this issue:

```
14:24:24.420 [error] GenServer ExAws.Config.AuthCache terminating
** (RuntimeError) ConfigParser required to use
    (ex_aws) lib/ex_aws/credentials_ini.ex:78: ExAws.CredentialsIni.security_credentials/1
    (ex_aws) lib/ex_aws/config/auth_cache.ex:63: ExAws.Config.AuthCache.refresh_awscli_config/3
    (ex_aws) lib/ex_aws/config/auth_cache.ex:46: ExAws.Config.AuthCache.handle_call/3
    (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:690: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.569.0>): {:refresh_awscli_config, "profile", 30000}
State: ExAws.Config.AuthCache
Client #PID<0.569.0> is alive
```

Using this config:

```
config :ex_aws,
  secret_access_key: [{:awscli, "profile", 30}],
  access_key_id: [{:awscli, "profile", 30}],
  awscli_auth_adapter: ExAws.STS.AuthCache.AssumeRoleCredentialsAdapter
```

Shouldn't `configparser_ex` be included in the `mix.exs` of this module, or at least mentioned in the `README.md` ?

**Comment by os6sense** [comment]
It's mentioned in the ex_aws readme (https://github.com/ex-aws/ex_aws) but yes, this bit me too

**Comment by benwilson512** [comment]
Mentioning it in the readme here would be good, PR welcome.

**Comment by speeddragon** [comment]
Created this one, https://github.com/ex-aws/ex_aws_sts/pull/14

**Comment by Wlojtek** [comment]
> https://github.com/ex-aws/ex_aws

and me too! 😄

**Comment by Wlojtek** [comment]
> It's mentioned in the ex_aws readme (https://github.com/ex-aws/ex_aws) but yes, this bit me too

@os6sense 
and me too! 😄
