### ISSUE TITLE
Issue because ExAws.CredentialsIni functions were moved 

### ISSUE THREAD

**Issue by alexandrubagu** [ex-aws/ex_aws_sts#25]
Hey,

Can you please release a new hex version with current code (master) ? 

When using these versions:
```elixir
mix hex.outdated | grep ex_aws
ex_aws                  2.2.3    2.2.3   Up-to-date       
ex_aws_sts              2.1.0    2.1.0   Up-to-date
```

We are facing the following problem:
```elixir
[error] GenServer ExAws.Config.AuthCache terminating
** (UndefinedFunctionError) function ExAws.CredentialsIni.security_credentials/1 is undefined (module ExAws.CredentialsIni is not available)
    ExAws.CredentialsIni.security_credentials("MY_CONFIG_NAME_HERE")
    (ex_aws_sts 2.1.0) lib/ex_aws/sts/auth_cache/assume_role_credentials_adapter.ex:15: ExAws.STS.AuthCache.AssumeRoleCredentialsAdapter.adapt_auth_config/4
    (ex_aws 2.2.2) lib/ex_aws/config/auth_cache.ex:75: ExAws.Config.AuthCache.refresh_awscli_config/3
    (ex_aws 2.2.2) lib/ex_aws/config/auth_cache.ex:50: ExAws.Config.AuthCache.handle_call/3
    (stdlib 3.14.1) gen_server.erl:715: :gen_server.try_handle_call/4
    (stdlib 3.14.1) gen_server.erl:744: :gen_server.handle_msg/6
    (stdlib 3.14.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

`ex_aws_sts` is trying to use `ExAws.CredentialsIni` functions which were moved to another module:

This was fixed on master but not released to hex. 
https://github.com/ex-aws/ex_aws_sts/commit/ae0a2197463570f03f8c8865eeab6ea1b8c31ad4#diff-1906e43cf2448749a207c1482cf8efad3ff8fb61bbfce0577bba8142a9043f3e

Workaround: 
```elixir
{:ex_aws_sts, github: "ex-aws/ex_aws_sts", ref: "6ac699b"}
```

Thanks, Alex

**Comment by vanetix** [comment]
Version 2.2.0 is out on hex.pm now, sorry for the delay. I'll go ahead and close this issue.

**Comment by alexandrubagu** [comment]
@vanetix no problem, thanks a lot
